# minimal unit test environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  ### environment-test.yml ###
  # build
  - pip
  - doit
  # run
  - jupyterlite-pyodide-kernel >=0.3.1,<0.4.0
  - jupyterlite-core >=0.3.0,<0.4.0
  - pyodide-lock ==0.1.0a4
  - tornado
  - jinja2
  - python-libarchive-c
  # test
  - pytest >=8,<9
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###
