# full development environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # lint
  - ruff >=0.3.0

  ### environment-test.yml ###
  # build
  - pip
  - doit
  # run
  - jupyterlite-pyodide-kernel >=0.3.1,<0.4.0
  - jupyterlite-core >=0.3.0,<0.4.0
  - pyodide-lock ==0.1.0a4
  - tornado
  - jinja2
  - python-libarchive-c
  # test
  - pytest >=8,<9
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###

  ### environment-docs.yml ###
  # docs
  - sphinx
  - myst-parser
  - pydata-sphinx-theme
  # demo
  - jupyterlab >=4.1,<4.2
  - ipywidgets >=8.1,<8.2
  ### environment-docs.yml ###
